name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ~/deploy-scripts/deploy-production.sh
